accounts/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', user_logout, name='logout'),
    path('profile_update/', UserUpdateView.as_view(), name='profile_update'),
    path('change_password/', ChangePassword.as_view(), name='change_password'),
]

bank_management/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('transactions/', include('transactions.urls')),
]

transactions/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('deposite/', DepositeView.as_view(), name='deposite'),
    path('withdraw/', WithdrawMoney.as_view(), name='withdraw'),
    path('loan_request/', LoanRequestView.as_view(), name='loan_request'),
    path('loan_list/', LoanListView.as_view(), name='loan_list'),
    path('report/', TransactionReportView.as_view(), name='report'),
    path('loan/<int:loan_id>', PayLoanView.as_view(), name='pay_loan'),
    path('transfer_money', TransferMoneyView.as_view(), name='transfer_money'),
]

transactions/models.py
from django.db import models
from accounts.models import UserBankAccount
from .constants import TRANSACTION_TYPE

# Create your models here.
class Transaction(models.Model):
    account = models.ForeignKey(UserBankAccount, on_delete=models.CASCADE, related_name='transactions')
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    balance_after_transaction = models.DecimalField(max_digits=12, decimal_places=2)
    transaction_type = models.IntegerField(choices=TRANSACTION_TYPE, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    loan_approve = models.BooleanField(default=False)

    class Meta:
        ordering = ['timestamp']

class BankSettings(models.Model):
    is_bankrupt = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.is_bankrupt}"

transactions/forms.py
from django import forms
from .models import Transaction
from accounts.models import UserBankAccount
from datetime import datetime
from .constants import TRANSFER_OUT, TRANSFER_IN

class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['amount', 'transaction_type']

    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account')
        super().__init__(*args, **kwargs)
        self.fields['transaction_type'].disabled = True # This will disable the transaction_type field
        self.fields['transaction_type'].widget = forms.HiddenInput() # This will hide the transaction_type field

    def save(self, commit=True):
        self.instance.account = self.account
        self.instance.balance_after_transaction = self.account.balance
        return super().save()
    

class DepositeForm(TransactionForm):
    def clean_amount(self):
        min_deposite_amount = 500
        amount = self.cleaned_data['amount']
        if amount < min_deposite_amount:
            raise forms.ValidationError(f"Minimum deposite amount is BDT {min_deposite_amount}")
        return amount
    

class WithdrawForm(TransactionForm):
    def clean_amount(self):
        account = self.account
        min_withraw = 500
        max_withdraw = 500000
        balance = account.balance
        amount = self.cleaned_data['amount']

        if amount < min_withraw:
            raise forms.ValidationError(f"Minimum withdraw amount is BDT {min_withraw}")
        
        if amount > max_withdraw:
            raise forms.ValidationError(f'Maximum withdraw amount is BDT {max_withdraw}')
        
        if balance < amount:
            raise forms.ValidationError("Insufficient balance, You have only BDT {balance} in your account")
        
        return amount
    
class LoanRequestForm(TransactionForm):
    def clean_amount(self):
        amount = self.cleaned_data['amount']

        return amount
    
class TransferMoneyForm(forms.Form):
    account_no = forms.IntegerField()
    amount = forms.DecimalField(max_digits=10, decimal_places=2)

    def __init__(self, *args, **kwargs):
        self.sender_account = kwargs.pop('sender_account')
        super().__init__(*args, **kwargs)
        self.receiver_account = None

    def clean_account_no(self):
        account_no = self.cleaned_data['account_no']

        try:
            receiver_account = UserBankAccount.objects.get(account_no = account_no)
        except UserBankAccount.DoesNotExist:
            raise forms.ValidationError("Invalid account number")
        
        if receiver_account == self.sender_account:
            raise forms.ValidationError("You can't transfer money to your own account")
        
        self.receiver_account = receiver_account
        return account_no
    
    def clean_amount(self):
        min_transfer = 500
        amount = self.cleaned_data['amount']

        if amount < min_transfer:
            raise forms.ValidationError(f"Minimum transfer amount is BDT {min_transfer}")
        
        max_transfer = 500000

        if amount > max_transfer:
            raise forms.ValidationError(f"Maximum transfer amount is BDT {max_transfer}")
        
        if self.sender_account.balance < amount:
            raise forms.ValidationError("Insufficient balance")
        
        return amount
    
    def save(self):
        amount = self.cleaned_data['amount']

        self.sender_account.balance -= self.cleaned_data['amount']
        self.receiver_account.balance += self.cleaned_data['amount']
        self.sender_account.save(update_fields = ['balance'])
        self.receiver_account.save(update_fields = ['balance'])

        Transaction.objects.create(
            account=self.sender_account,
            amount=-amount,  # Deducted amount as negative
            transaction_type= TRANSFER_OUT,
            balance_after_transaction = self.sender_account.balance,
            # description=f'Transfer to {self.receiver_account.account_no}',
            timestamp=datetime.now(),
        )

        # Create transaction for receiver
        Transaction.objects.create(
            account=self.receiver_account,
            amount=amount,  # Added amount as positive
            transaction_type= TRANSFER_IN,
            balance_after_transaction = self.receiver_account.balance,
            # description=f'Transfer from {self.sender_account.account_no}',
            timestamp=datetime.now(),
        )

transactions/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, CreateView
from django.views import View
from .models import Transaction, BankSettings
from .forms import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .constants import DEPOSIT, WITHDRAWAL, LOAN, LOAN_PAID, TRANSFER_IN, TRANSFER_OUT
from django.contrib import messages
from datetime import datetime
from django.db.models import Sum
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import render_to_string

# Create your views here.

def send_transaction_email(user, amount, subject, template):
    mail_subject = 'Deposite Confirmation'
    message = render_to_string(template, { 
        'user' : user, 
        'amount' : amount, 
    })
    to_email = user.email
    send_mail = EmailMultiAlternatives(subject, '', to=[to_email])
    send_mail.attach_alternative(message, 'text/html')
    send_mail.send()


class TransactionCreateView(LoginRequiredMixin, CreateView):
    model = Transaction
    template_name = 'transaction_form.html'
    form_class = TransactionForm
    title = ''
    success_url = reverse_lazy('report')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'account' : self.request.user.account
        })
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title' : self.title
        })
        return context
    
class DepositeView(TransactionCreateView):
    form_class = DepositeForm
    title = 'Deposite BDT'

    def get_initial(self):
        initial = super().get_initial()
        initial.update({
            'transaction_type' : DEPOSIT
        })
        return initial
    
    def form_valid(self, form):
        print(self.request.POST)
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account
        account.balance += amount
        account.save(update_fields = ['balance'])
        messages.success(self.request, f'BDT {amount} has been successfully deposited to your account')
        send_transaction_email(self.request.user, amount, 'Deposite Confirmation', 'deposite_email.html')
        return super().form_valid(form)

class WithdrawMoney(TransactionCreateView):
    form_class = WithdrawForm
    title = 'Withdraw BDT'

    def dispatch(self, request, *args, **kwargs):
        # Dynamically check if the bank is bankrupt
        bank_settings = BankSettings.objects.first()
        if bank_settings and bank_settings.is_bankrupt:
            messages.error(request, "The bank is currently bankrupt. WithDrawn are not allowed.")
            return redirect('home')  # Redirect to a safe page
        return super().dispatch(request, *args, **kwargs)
    

    def get_initial(self):
        initial = super().get_initial()
        initial.update({
            'transaction_type' : WITHDRAWAL
        })
        return initial
    
    def form_valid(self, form):
        amount = form.cleaned_data['amount']
        account = self.request.user.account
        account.balance -= amount
        account.save(update_fields = ['balance'])
        messages.success(self.request, f'BDT {amount} has been successfully withdarw from your account')
        send_transaction_email(self.request.user, amount, 'Withdrawl Confirmation', 'withdrawal.html')
        return super().form_valid(form)
    
class LoanRequestView(TransactionCreateView):
    form_class = LoanRequestForm
    title = 'Requesting for Loan'

    def dispatch(self, request, *args, **kwargs):
        # Dynamically check if the bank is bankrupt
        bank_settings = BankSettings.objects.first()
        if bank_settings and bank_settings.is_bankrupt:
            messages.error(request, "The bank is currently bankrupt. Loan Request View not allowed.")
            return redirect('home')  # Redirect to a safe page
        return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        initial = super().get_initial()
        initial.update({
            'transaction_type' : LOAN
        })
        return initial
    
    def form_valid(self, form):
        amount = form.cleaned_data['amount']
        current_loan_count = Transaction.objects.filter(account = self.request.user.account, transaction_type = LOAN, loan_approve = True).count()
        if current_loan_count >= 3:
            messages.error(self.request, 'You have already 3 active loans, first return them to get another loan')
            return super().form_invalid(form)
        messages.success(self.request, f'BDT {amount} of loan Request has been sent to the bank authority')
        send_transaction_email(self.request.user, amount, 'Loan Application Status', 'loan_application.html')
        return super().form_valid(form)

class TransactionReportView(LoginRequiredMixin, ListView):
    model = Transaction
    template_name = 'transaction_report.html'
    balance = 0

    def get_queryset(self):
        queryset = super().get_queryset().filter(account = self.request.user.account)

        start_date_str = self.request.GET.get('start_date')
        end_date_str = self.request.GET.get('end_date')

        if start_date_str and end_date_str:
            start_date = datetime.strptime(start_date_str, '%Y-%m-%d')
            end_date = datetime.strptime(end_date_str, '%Y-%m-%d')

            queryset = queryset.filter(timestamp__date__gte = start_date, timestamp__date__lte = end_date)

            self.balance =  self.balance = queryset.aggregate(Sum('amount'))['amount__sum'] or 0
        else:
            self.balance = self.request.user.account.balance

        return queryset.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'account' : self.request.user.account,
            'curr_balance' : self.balance
        })
        return context


class PayLoanView(LoginRequiredMixin, View):
    def get(self, request, loan_id):
        loan = get_object_or_404(Transaction, id=loan_id)

        if loan.loan_approve:
            user_account = loan.account
            if loan.amount < user_account.balance:
                user_account.balance -= loan.amount
                loan.balance_after_transaction = user_account.balance
                user_account.save()
                loan.transaction_type = LOAN_PAID
                loan.save()
                messages.success(request, 'Loan has been successfully paid')
                send_transaction_email(self.request.user, loan.amount, 'Loan Repayment Confirmation', 'loan_confirmation.html')
                return redirect('report')
            else:
                messages.error(request, 'You do not have sufficient balance to pay the loan')
                return redirect('report')


class LoanListView(LoginRequiredMixin, ListView):
    model = Transaction
    template_name = 'loan_request.html'
    context_object_name = 'loans'

    def get_queryset(self):
        user_account = self.request.user.account
        queryset = super().get_queryset().filter(account = user_account, transaction_type = LOAN)
        return queryset


class TransferMoneyView(LoginRequiredMixin, View):
    template_name = 'transfer_money.html'
    title = "Transfer Money"

    def dispatch(self, request, *args, **kwargs):
        # Dynamically check if the bank is bankrupt
        bank_settings = BankSettings.objects.first()
        if bank_settings and bank_settings.is_bankrupt:
            messages.error(request, "The bank is currently bankrupt. Transfer Money is not allowed.")
            return redirect('home')  # Redirect to a safe page
        return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        initial = super().get_initial()
        initial.update({
            'transaction_type' : TRANSFER_OUT
        })

    def get(self, request):
        form = TransferMoneyForm(sender_account = request.user.account)
        return render(request, self.template_name, {'form' : form, 'title' : self.title})
    
    def post(self, request):
        form = TransferMoneyForm(request.POST, sender_account = request.user.account)
        if form.is_valid():
            form.save()
            messages.success(request, 'Money has been successfully transferred')
            receiver_account = form.receiver_account
            send_transaction_email(request.user, form.cleaned_data['amount'], "Transfer Confirmation", 'transfer_email.html')
            send_transaction_email(receiver_account.user, form.cleaned_data['amount'], "Transfer Confirmation", 'transfer_email.html')
            return redirect('report')
        return render(request, self.template_name, {'form' : form, 'title' : self.title})

transactions/templates/deposite_email.html
<h3> Hello Mr. {{user.first_name}} {{user.last_name}}</h3>

<p>Thank you for depositing {{amount}} to your account. Your current account balance is BDT {{user.account.balance}}</p>
<p>Thanks for Banking with us </p>

<p>Regards</p>
<p>Brak Bank</p>

transactions/templates/loan_application.html
<h3> Hello Mr. {{user.first_name}} {{user.last_name}}</h3>

<p>You have requested for BDT {{amount}} Loan. Thank you for applying, we will get back to you soon with confirmation message after verifying all</p>
<p>Thanks for Banking with us </p>

<p>Regards</p>
<p>Brak Bank</p>

transactions/templates/loan_approve.html
<h3> Hello Mr. {{user.first_name}} {{user.last_name}}</h3>

<p>Your requested loan of BDT {{amount}} has been approved by Bank Authority. Your current account balance is BDT {{user.account.balance}}</p>
<p>Thanks for Banking with us </p>

<p>Regards</p>
<p>Brak Bank</p>

transactions/templates/loan_confirmation.html
<h3> Hello Mr. {{user.first_name}} {{user.last_name}}</h3>

<p>Thank youf for your loan Payment of BDT {{amount}}.</p>
<p>Thanks for Banking with us </p>

<p>Regards</p>
<p>Brak Bank</p>

transactions/templates/loan_request.html
{% extends 'base.html' %} 
{% block head_title %}{{ title }}{% endblock %} 
{% block content %}
<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
  <h1 class="font-bold text-3xl text-center pb-5 pt-2">Loan Report</h1>
  <hr />
  <table
    class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500"
  >
    <thead class="bg-purple-900 text-white text-left">
      <tr
        class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold"
      >
        <th class="px-4 py-2">LOAN ID</th>
        <th class="px-4 py-2">Loan Amount</th>
        <th class="px-4 py-2">Loan Approved</th>
        <th class="px-4 py-2">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for loan in loans %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
         {{ loan.id }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span class="px-2 py-1 font-bold leading-tight rounded-sm text-green-700 bg-green-100"> 
            {{ loan.amount }} 
          </span>
        </td>
        <td class="px-4 py-2">
          {{ loan.loan_approve }}
        </td>
        <td class="px-4 py-2">
          {% if loan.loan_approve %}
          <a class="font-bold bg-red-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" href='{% url "pay_loan" loan.id %}'>Pay</a>
          {% else %}
          <p class="font-bold text-red-700 bg-red-100">Loan Pending</p>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

transactions/templates/transaction_form.html
{% extends 'base.html' %} 
{% block head_title %}{{ title }}{% endblock %} 

{% block content %}

<div class="w-full flex mt-5 justify-center ">
    <div class="bg-white w-5/12 rounded-lg">
        {% if title == 'Requesting for Loan' %}
<div><a class="font-bold text-blue text-center pb-5 pt-10 px-5" href="{% url 'loan_list' %}">View All Loan List</a></div>
        {% endif %}
        
        <h1 class="font-bold text-3xl text-center pb-5 pt-10 px-5">{{ title }}</h1>
        <form method="post" class="px-8 pt-6 pb-8 mb-4">
            {% csrf_token %}

            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="amount"> Amount </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder="Amount">
            </div>
            {% if form.amount.errors %} {% for error in form.amount.errors %}
            <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
            {% endfor %} {% endif %}
            <div class="flex w-full justify-center">
                <button class="bg-blue-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" type="submit"> Submit </button>
            </div>
        </form>
    </div>
    
</div>
{% endblock %}

transactions/templates/transaction_report.html
{% extends 'base.html' %} 
{% load static %}
{% load humanize %}
{% block head_title %} Transaction Report {% endblock %} 
{% block content %}


<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
  <h1 class="font-bold text-3xl text-center pb-5 pt-2">Transaction Report</h1>
  <hr />
  <form method="get" action="{% url 'report' %}">
    <div class="flex justify-center">
      <div class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12 mx-2">
        <label for="start_date">From:</label>
        <input class="appearance-none w-full outline-none focus:outline-none active:outline-none" type="date" id="start_date" name="start_date"/>
      </div>
 
      <div class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12">
        <label for="end_date">To:</label>
        <input class="appearance-none w-full outline-none focus:outline-none active:outline-none" type="date" id="end_date" name="end_date"/>
      </div>
      <div class="mt-10 pl-3 pr-2 flex justify-between items-center relative w-4/12">
        <button class="bg-blue-900 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit"> Filter </button>
      </div>
    </div>
  </form>
  <table class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500" >
    <thead class="bg-purple-900 text-white text-left">
      <tr class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold">
        <th class="px-4 py-2">Date</th>
        <th class="px-4 py-2">Transaction Type</th>
        <th class="px-4 py-2">Amount</th>
        <th class="px-4 py-2">Balance After Transaction</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in object_list %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
          {{ transaction.timestamp|date:"F d, Y h:i A" }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span class="px-2 py-1 font-bold leading-tight rounded-sm {% if transaction.get_transaction_type_display == 'Withdrawal' %} text-red-700 bg-red-100 {% else %} text-green-700 bg-green-100 {% endif %}" >
            {{ transaction.get_transaction_type_display }}
          </span>
        </td>
        <td class="px-4 py-2"> BDT {{ transaction.amount|floatformat:2|intcomma }} </td>
        <td class="px-4 py-2"> BDT {{ transaction.balance_after_transaction|floatformat:2|intcomma }} </td>
      </tr>
      {% endfor %}
      <tr class="bg-gray-800 text-white">
        <th class="px-4 py-2 text-right" colspan="3">Total Balance</th>
        <th class="px-4 py-2 text-left">
          BDT {{ curr_balance|floatformat:2|intcomma }}
        </th>
      </tr>
    </tbody>
  </table>
</div>
<br>
{% endblock %}

transactions/templates/transfer_email.html
<h3> Hello Mr. {{user.first_name}} {{user.last_name}}</h3>

<p>You have successfully transfered {{amount}} to your {{account_no}}. Your current account balance is BDT {{user.account.balance}}</p>
<p>Thanks for Banking with us </p>

<p>Regards</p>
<p>Brak Bank</p>

transactions/templates/transfer_money.html
{% extends 'base.html' %} 
{% block head_title %}{{ title }}{% endblock %} 

{% block content %}

<div class="w-full flex mt-5 justify-center ">
    <div class="bg-white w-5/12 rounded-lg">
        {% if title == 'Requesting for Loan' %}
<div><a class="font-bold text-blue text-center pb-5 pt-10 px-5" href="{% url 'loan_list' %}">View All Loan List</a></div>
        {% endif %}
        
        <h1 class="font-bold text-3xl text-center pb-5 pt-10 px-5">{{ title }}</h1>
        <form method="post" class="px-8 pt-6 pb-8 mb-4">
            {% csrf_token %}

            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="amount"> Account No </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="account_no" id="account_no" type="number" required placeholder="Account Number">
            </div>

            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="amount"> Amount </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder="Amount">
            </div>
            {% if form.account_no.errors %} {% for error in form.account_no.errors %}
            <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
            {% endfor %} {% endif %}
            <div class="flex w-full justify-center">
                <button class="bg-blue-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" type="submit"> Submit </button>
            </div>
        </form>
    </div>
    
</div>
{% endblock %}

transactions/templates/transfer_rec.html
<h3> Hello Mr. {{user.first_name}} {{user.last_name}}</h3>

<p>You have received {{amount}} from account no : {{request.user.account}}. Your current account balance is BDT {{user.account.balance}}</p>
<p>Thanks for Banking with us </p>

<p>Regards</p>
<p>Brak Bank</p>

transactions/templates/withdrawal.html
<h3> Hello Mr. {{user.first_name}} {{user.last_name}}</h3>

<p>Your withdraw BDT {{amount}} has been successful. Your current account balance is BDT {{user.account.balance}}</p>
<p>Thanks for Banking with us </p>

<p>Regards</p>
<p>Brak Bank</p>